# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"


class Ui_CaeserCipher(object):
    def setupUi(self, CaeserCipher):
        CaeserCipher.setObjectName("CaeserCipher")
        CaeserCipher.resize(923, 688)
        self.centralwidget = QtWidgets.QWidget(CaeserCipher)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(220, 130, 511, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(220, 310, 511, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(220, 390, 511, 141))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 66, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 180, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 320, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 420, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 560, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 560, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        CaeserCipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CaeserCipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 26))
        self.menubar.setObjectName("menubar")
        CaeserCipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CaeserCipher)
        self.statusbar.setObjectName("statusbar")
        CaeserCipher.setStatusBar(self.statusbar)

        self.retranslateUi(CaeserCipher)
        QtCore.QMetaObject.connectSlotsByName(CaeserCipher)

    def retranslateUi(self, CaeserCipher):
        _translate = QtCore.QCoreApplication.translate
        CaeserCipher.setWindowTitle(_translate("CaeserCipher", "MainWindow"))
        self.label.setText(_translate("CaeserCipher", "CAESAR CIPHER"))
        self.label_2.setText(_translate("CaeserCipher", "2280601165 - LÝ TRẦN HUY"))
        self.label_3.setText(_translate("CaeserCipher", "Plain text:"))
        self.label_4.setText(_translate("CaeserCipher", "Key:"))
        self.label_5.setText(_translate("CaeserCipher", "Cipher text:"))
        self.pushButton.setText(_translate("CaeserCipher", "Encrypt"))
        self.pushButton_2.setText(_translate("CaeserCipher", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CaeserCipher = QtWidgets.QMainWindow()
    ui = Ui_CaeserCipher()
    ui.setupUi(CaeserCipher)
    CaeserCipher.show()
    sys.exit(app.exec_())
