# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_playfair(object):
    def setupUi(self, playfair):
        playfair.setObjectName("playfair")
        playfair.resize(869, 689)
        self.flayfair = QtWidgets.QWidget(playfair)
        self.flayfair.setObjectName("flayfair")
        self.label_5 = QtWidgets.QLabel(self.flayfair)
        self.label_5.setGeometry(QtCore.QRect(60, 424, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.flayfair)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 564, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser_2 = QtWidgets.QTextEdit(self.flayfair)
        self.textBrowser_2.setGeometry(QtCore.QRect(220, 314, 511, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextEdit(self.flayfair)
        self.textBrowser_3.setGeometry(QtCore.QRect(220, 394, 511, 141))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_4 = QtWidgets.QLabel(self.flayfair)
        self.label_4.setGeometry(QtCore.QRect(70, 324, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextEdit(self.flayfair)
        self.textBrowser.setGeometry(QtCore.QRect(220, 134, 511, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.flayfair)
        self.pushButton.setGeometry(QtCore.QRect(250, 564, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.flayfair)
        self.label.setGeometry(QtCore.QRect(330, 14, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.flayfair)
        self.label_3.setGeometry(QtCore.QRect(70, 184, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.flayfair)
        self.label_2.setGeometry(QtCore.QRect(360, 70, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        playfair.setCentralWidget(self.flayfair)
        self.menubar = QtWidgets.QMenuBar(playfair)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 26))
        self.menubar.setObjectName("menubar")
        playfair.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(playfair)
        self.statusbar.setObjectName("statusbar")
        playfair.setStatusBar(self.statusbar)

        self.retranslateUi(playfair)
        QtCore.QMetaObject.connectSlotsByName(playfair)

    def retranslateUi(self, playfair):
        _translate = QtCore.QCoreApplication.translate
        playfair.setWindowTitle(_translate("playfair", "MainWindow"))
        self.label_5.setText(_translate("playfair", "Cipher text:"))
        self.pushButton_2.setText(_translate("playfair", "Decrypt"))
        self.label_4.setText(_translate("playfair", "Key:"))
        self.pushButton.setText(_translate("playfair", "Encrypt"))
        self.label.setText(_translate("playfair", "PLAY FAIR CIPHER"))
        self.label_3.setText(_translate("playfair", "Plain text:"))
        self.label_2.setText(_translate("playfair", "2280601165 - LÝ TRẦN HUY"))
