# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/railfence.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RailFence(object):
    def setupUi(self, RailFence):
        RailFence.setObjectName("RailFence")
        RailFence.resize(857, 682)
        self.centralwidget = QtWidgets.QWidget(RailFence)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 140, 511, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(200, 320, 511, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(200, 400, 511, 141))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 330, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 570, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 570, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 76, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 430, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 20, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        RailFence.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RailFence)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 26))
        self.menubar.setObjectName("menubar")
        RailFence.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RailFence)
        self.statusbar.setObjectName("statusbar")
        RailFence.setStatusBar(self.statusbar)

        self.retranslateUi(RailFence)
        QtCore.QMetaObject.connectSlotsByName(RailFence)

    def retranslateUi(self, RailFence):
        _translate = QtCore.QCoreApplication.translate
        RailFence.setWindowTitle(_translate("RailFence", "Rail Fence Cipher"))
        self.label_3.setText(_translate("RailFence", "Plain text:"))
        self.label_4.setText(_translate("RailFence", "Key:"))
        self.pushButton.setText(_translate("RailFence", "Encrypt"))
        self.pushButton_2.setText(_translate("RailFence", "Decrypt"))
        self.label_2.setText(_translate("RailFence", "2280601165 - LÝ TRẦN HUY"))
        self.label_5.setText(_translate("RailFence", "Cipher text:"))
        self.label.setText(_translate("RailFence", "RAIL FENCE CIPHER"))
