# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vigenere(object):
    def setupUi(self, Vigenere):
        Vigenere.setObjectName("Vigenere")
        Vigenere.resize(990, 738)
        self.centralwidget = QtWidgets.QWidget(Vigenere)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(250, 330, 511, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(250, 410, 511, 141))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 580, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 340, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(250, 150, 511, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 86, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 580, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 200, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 440, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Vigenere.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Vigenere)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 26))
        self.menubar.setObjectName("menubar")
        Vigenere.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Vigenere)
        self.statusbar.setObjectName("statusbar")
        Vigenere.setStatusBar(self.statusbar)

        self.retranslateUi(Vigenere)
        QtCore.QMetaObject.connectSlotsByName(Vigenere)

    def retranslateUi(self, Vigenere):
        _translate = QtCore.QCoreApplication.translate
        Vigenere.setWindowTitle(_translate("Vigenere", "MainWindow"))
        self.pushButton_2.setText(_translate("Vigenere", "Decrypt"))
        self.label_4.setText(_translate("Vigenere", "Key:"))
        self.label_2.setText(_translate("Vigenere", "2280601165 - LÝ TRẦN HUY"))
        self.pushButton.setText(_translate("Vigenere", "Encrypt"))
        self.label_3.setText(_translate("Vigenere", "Plain text:"))
        self.label_5.setText(_translate("Vigenere", "Cipher text:"))
        self.label.setText(_translate("Vigenere", "VIGENERE CIPHER"))
